### ISSUE TITLE
Add team level info

### ISSUE THREAD

**Issue by unkdrew** [naw-db/naw-db.github.io#8]

**Comment by MitchPleaseAllWorld** [comment]
I'd probably leave this one for a bit, as I'm still trying to gather all the data.

**Comment by unkdrew** [comment]
@MitchPleaseAllWorld Do you think we can annotate all the unknown fields as `?` rather than leaving them empty? I have marked the unknown player rank up drill requirements as `?` but have yet to cover other sheets.

**Comment by MitchPleaseAllWorld** [comment]
yeah that's a good idea actually, then hopefully people will see it and more readily share the info
